name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
      crate:
        description: 'Crate to release'
        required: true
        default: 'function-timer-macro'
        type: choice
        options:
          - function-timer-macro
          - function-timer

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - uses: taiki-e/install-action@cargo-hack
      - name: Test features
        run: cargo hack check --all --each-feature --clean-per-run --no-dev-deps
      - name: Echo
        run: echo ${{ github.event.inputs.release_type }}
      - name: Install
        run: cargo install cargo-edit
      - name: Bump new version
        run: |
          cargo set-version -p ${{ github.event.inputs.crate }} --bump ${{ github.event.inputs.release_type }}
          export VERSION=`cargo tree -p ${{ github.event.inputs.crate }} --depth 0 | grep ${{ github.event.inputs.crate }} | awk '{print $2}'`
          echo "VERSION=$VERSION"  >> $GITHUB_ENV
          if [[ ${{ github.event.inputs.release_type }} != "patch" ]] && [[ ${{ github.event.inputs.crate }} == "function-timer-macro" ]]; then
            cargo set-version -p function-timer --bump ${{ github.event.inputs.release_type }}
          fi
      - name: Commit new version
        run: |
          git config user.name "$env.GITHUB_ACTOR"
          git config user.email "$env.GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Prepare ${{ env.VERSION }}"
          git push
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION }}
      - name: Publish
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p ${{ github.event.inputs.crate }}
          if [[ ${{ github.event.inputs.release_type }} != "patch" ]] && [[ ${{ github.event.inputs.crate }} == "function-timer-macro" ]]; then
            cargo publish -p function-timer
          fi
      - name: Check
        run: cat Cargo.toml

